DatabaseMirror database.clamav.net
DatabaseDirectory "C:/Users/jepit/OneDrive/Työpöytä/desktopsoftware/duplicate-file-finder/source-code/dff_test_8i7hoka_/freshclam"
UpdateLogFile "C:/Users/jepit/OneDrive/Työpöytä/desktopsoftware/duplicate-file-finder/source-code/dff_test_8i7hoka_/freshclam.log"
CVDCertsDirectory "C:/Users/jepit/OneDrive/Työpöytä/desktopsoftware/duplicate-file-finder/source-code/dff_test_8i7hoka_/clamav-certs"
ConnectTimeout 30
ReceiveTimeout 60
