DatabaseMirror database.clamav.net
DatabaseDirectory "C:/Users/jepit/OneDrive/Työpöytä/desktopsoftware/duplicate-file-finder/source-code/dff_test_92iwbq26/freshclam"
UpdateLogFile "C:/Users/jepit/OneDrive/Työpöytä/desktopsoftware/duplicate-file-finder/source-code/dff_test_92iwbq26/freshclam.log"
CVDCertsDirectory "C:/Users/jepit/OneDrive/Työpöytä/desktopsoftware/duplicate-file-finder/source-code/dff_test_92iwbq26/clamav-certs"
ConnectTimeout 30
ReceiveTimeout 60
